cabinet/urls.py
from django.conf.urls import url

from . import views

app_name = 'cabinet'
urlpatterns = [
    # ex: /cabinet/4
    url(r'^(?P<user_id>[0-9]+)/$', views.viewCabinet, name='view_cabinet'),
    # ex: /cabinet/4/edit
    url(r'^(?P<user_id>[0-9]+)/edit/$', views.editProfile, name='edit_profile'),
]

tasks/urls.py
from django.conf.urls import url

from . import views
from .views import TaskDetailView
from django.contrib.auth.decorators import login_required

app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.tasks, name='tasks'),
    # ex: /theme/
    url(r'^theme/$', views.tasks, name='tasks'),
    # ex: /theme/API
    url(r'^theme/(?P<theme>[^0-9]+)/$', views.theme_tasks, name='theme_tasks'),
    # ex: /10
    url(r'^(?P<pk>[0-9]+)/$', login_required(TaskDetailView.as_view()), name='task'),
    # ex: /API-01:
    url(r'^(?P<code>([^0-9]+)-([0-9]+))/$', views.task_by_code, name='task_by_code'),
    # ex: /10/start
    url(r'^(?P<task_id>[0-9]+)/start$', views.start, name='start'),
    # ex: /10/stop
    url(r'^(?P<task_id>[0-9]+)/stop$', views.stop, name='stop'),
    # ex: /10/continue
    url(r'^(?P<task_id>[0-9]+)/come_back$', views.come_back, name='come_back'),
    # ex: /10/finish
    url(r'^(?P<task_id>[0-9]+)/finish$', views.finish, name='finish'),
]

test_lab_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.main, name='main'),
    url(r'^register/$', views.register, name='register'),
    url(r'^about/$', views.about, name='about'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

cabinet/models.py
from django.db import models

# Create your models here.

cabinet/forms.py
from django.contrib.auth.models import User
from django import forms

class UserCabinetForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')

cabinet/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
# Create your views here.
import logging
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from .forms import UserCabinetForm
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
@login_required()
def viewCabinet(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    context = {"user": user}
    return render(request, 'cabinet/cabinet_main.html', context)

@login_required()
def editProfile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # this variable is needed to hide unique username error which is shown in most cases when user edits
    #   his/her profile:
    show_unique_username_error = False
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserCabinetForm(data=request.POST)
        username_from_post = request.POST['username']
        email_from_post = request.POST['email']

        if user_form.has_error('username', "unique") and not user_form.has_error('email'):
            logging.warning("username from username field = {0}, username from request = {1}"
                            .format(username_from_post, request.user.username))
            if username_from_post == request.user.username:
                # in case username is the same as from request - user wants to change e-mail (or/and other details)
                #   - in this case we are saving details for this user (except username):
                user.email = email_from_post
                user.save()
                return HttpResponseRedirect(reverse('cabinet:view_cabinet',args=(user.id,)))
            else:
                # in case username specified in the POST data - is not the same as logged in user -
                #   we will render the form with validation error:
                show_unique_username_error = True
                logging.warning("User tried to change the username, but it already exists")
        else:
            if user_form.is_valid():
                user.username = username_from_post
                user.email = email_from_post
                user.save()
                return HttpResponseRedirect(reverse('cabinet:view_cabinet',args=(user.id,)))
            else:
                print(user_form.errors)
    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        # NEED TO INSERT Model data in forms:
        data = {
            "username": user.username,
            "email": user.email,
        }
        user_form = UserCabinetForm(data)
    context = {"user_form": user_form, "show_unique_username_error": show_unique_username_error}
    logging.warning(show_unique_username_error)
    return render(request, 'cabinet/cabinet_edit.html', context)

cabinet/templates/cabinet/cabinet_edit.html
{% extends "base.html" %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
{% load static %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li><a href="{% url 'cabinet:view_cabinet' user.id %}">Личный кабинет</a></li>
        <li class="active">Редактирование профиля</li>
    </ol>
    <div class="page-header">
        <h3>Редактирование профиля {{ user.username }}</h3>
    </div>
    {% if user.is_authenticated %}
        <form id="user_form" method="post" action="{% url 'cabinet:edit_profile' user.id %}" enctype="multipart/form-data">
            <div class="form-group row">
                <div class="col-md-6">
                    {% csrf_token %}
                    {% if user_form.non_field_errors %}
                        <div class="alert alert-warning" role="alert">
                                    <p>{{ user_form.non_field_errors }}</p>
                                </div>
                    {% endif %}
                    <label for="user_name">Имя пользователя</label>
                    {% if show_unique_username_error %}
                        <div class="alert alert-warning" role="alert">
                            <p>{{ user_form.username.errors }}</p>
                        </div>
                    {% endif %}
                    <!--TODO: Form doesn't show error for username field. For example, when it's empty. Only unique
                     error is shown.-->

                    <input type="text" name="username" value="{{ user_form.username.value }}" size="50"
                           class="form-control" id="user_name"/>
                    {% if user_form.email.errors %}
                        <div class="alert alert-warning" role="alert">
                            <p>{{ user_form.email.errors }}</p>
                        </div>
                    {% endif %}
                    <label for="user_email">E-mail</label>
                    <input type="text" name="email" value="{{ user_form.email.value }}" size="50"
                           class="form-control" id="user_email"/>
                    {{ profile_form }}
                    <!-- Provide a button to click to submit the form. -->
                    <input type="submit" name="submit" value="Сохранить" class="btn btn-default"/>
                </div>
        </form>
    {% endif %}
</div>
{% endblock %}

cabinet/templates/cabinet/cabinet_main.html
{% extends "base.html" %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
{% load static %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li class="active">Личный кабинет</li>
    </ol>
    <div class="page-header">
        <h3>Личный кабинет {{ user.username }}</h3>
    </div>
    {% if user.is_authenticated %}
        Имя пользователя: {{ user.username }}<br>
        <a href="{% url 'cabinet:edit_profile' user.id %}">Редактировать профиль пользователя</a>
    {% endif %}
</div>
{% endblock %}