cabinet/urls.py
from django.conf.urls import url

from . import views

app_name = 'cabinet'
urlpatterns = [
    # ex: /cabinet/4
    url(r'^(?P<user_id>[0-9]+)/$', views.viewCabinet, name='view_cabinet'),
    # ex: /cabinet/4/edit
    url(r'^(?P<user_id>[0-9]+)/edit/$', views.editProfile, name='edit_profile'),
]

tasks/urls.py
from django.conf.urls import url

from . import views
from .views import TaskDetailView
from django.contrib.auth.decorators import login_required

app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.tasks, name='tasks'),
    # ex: /theme/
    url(r'^theme/$', views.tasks, name='tasks'),
    # ex: /theme/API
    url(r'^theme/(?P<theme>[^0-9]+)/$', views.theme_tasks, name='theme_tasks'),
    # ex: /10
    url(r'^(?P<pk>[0-9]+)/$', login_required(TaskDetailView.as_view()), name='task'),
    # ex: /API-01:
    url(r'^(?P<code>([^0-9]+)-([0-9]+))/$', views.task_by_code, name='task_by_code'),
    # ex: /10/start
    url(r'^(?P<task_id>[0-9]+)/start$', views.start, name='start'),
    # ex: /10/stop
    url(r'^(?P<task_id>[0-9]+)/stop$', views.stop, name='stop'),
    # ex: /10/continue
    url(r'^(?P<task_id>[0-9]+)/come_back$', views.come_back, name='come_back'),
    # ex: /10/finish
    url(r'^(?P<task_id>[0-9]+)/finish$', views.finish, name='finish'),
]

test_lab_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.main, name='main'),
    url(r'^register/$', views.register, name='register'),
    url(r'^about/$', views.about, name='about'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

templates/about.html
{% extends "base.html" %}

{% load static %}
{% block custom_static %}
    <!-- Custom styles for this template -->
    <link href="{% static "css/jumbotron-narrow.css" %}" rel="stylesheet">
{% endblock custom_static %}

{% block title %}О нас{% endblock %}

{% block content %}
<div class="container">
    {% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li class="active">О нас</li>
    </ol>
    {% endblock %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>{% block title %}Test Camp at SQA Days{% endblock title %}</title>

	{% load static %}
    <script src="{% static "js/react.js" %}"></script>
    <script src="{% static "js/react-dom.js" %}"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">
    {% block custom_static %}
    {% endblock custom_static %}
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <header class="container">
      <div id="menu" class="navbar navbar-default">
        <div class="navbar-header">
          <button class="btn navbar-toggle collapsed"
                  data-toggle="collapse"
                  data-target=".navbar-collapse"><span class="glyphicon glyphicon-chevron-down">
                  </span></button>
          {% block logo %}
          <div class="navbar-brand">
            <a href="{% url 'main' %}" id="logo">
                Test Camp at SQA Days
              <!--<img src="{% static "img/logo_0205_extra_small.png" %}">-->
            </a>
          </div>
          {% endblock logo %}
        </div>
        {% block navigation %}
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <!--<li class="nav"><a href="{% url 'about' %}">О нас</a></li>-->
              <!--<li class="nav"><a href="{% url 'stats' %}">Статистика</a></li>-->
            {% if user.is_authenticated %}
              <li class="nav"><a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
              <li class="nav"><a href="{% url 'register' %}">Регистрация</a></li>
              <li class="nav"><a href="{% url 'login' %}">Войти</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
      {% endblock navigation %}
    </header>
    <div>
      {% block content %}
        <div>
		{% if user.is_authenticated %}
			<span>Вы вошли как <a href="#">123</a></span>
            <h1>Welcome, {{ user.username }}!</h1>
            <p class="lead">Пусть вас не смущает серый фон, он будет другим, как только я найду место в Bootstrap шаблоне, где это можно сделать.</p>
          {% else %}
			<h1>Welcome!</h1>
            <p class="lead">Пусть вас не смущает серый фон, он будет другим, как только я найду место в Bootstrap шаблоне, где это можно сделать.</p>
            <p><a class="btn btn-lg btn-success" href="{% url 'register' %}" role="button">Регистрация</a></p>
		{% endif %}
        </div>
      {% endblock content %}
    </div>
    <div class="container">
      <footer class="footer">
        <p>&copy; 2017 On-the-knee United Web Design Studio.</p>
      </footer>
    </div>
    <script src='{% static "js/jquery-1.12.2.min.js" %}'></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    {% block more_scripts %}

    {% endblock more_scripts %}
  </body>
</html>

templates/contacts.html
{% extends "base.html" %}

{% block title %}Контакты{% endblock %}

{% block navigation %}
          <nav>
            <ul class="nav nav-pills pull-right">
                <li role="presentation"><a href="{% url 'main' %}">Главная</a></li>
			    <li role="presentation"><a href="{% url 'events' %}">События</a></li>
                <li role="presentation" class="active"><a href="#">Контакты</a></li>
			    {% if user.is_authenticated %}
				    <li role="presentation"><a href="{% url 'logout' %}">Выйти</a></li>
			    {% else %}
				<li role="presentation"><a href="{% url 'register' %}">Регистрация</a></li>
				<li role="presentation"><a href="{% url 'login' %}">Войти</a></li>
			{% endif %}
            </ul>
          </nav>
{% endblock %}

{% block content %}
          Здесь будут контакты.
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Войти на сайт{% endblock %}

{% block section_title %}
{% endblock section_title %}

{% block content %}
<div class="container">
    {% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li class="active">Войти</li>
    </ol>
    {% endblock %}
    {% if wrong_details %}
        <div class="alert alert-warning" role="alert">
            <p style="color:red">Введённые логин или пароль неправильны. Попробуйте еще раз.</p>
        </div>
    {% endif %}
    <form id="login_form" method="post" action="{% url 'login' %}">
        <div class="form-group row">
            <div class="col-md-6">
                {% csrf_token %}
                <label for="user_name">Имя пользователя</label>
                <input type="text" name="username" value="" size="50" class="form-control" id="user_name"
                       placeholder="Ваше имя"/>
                <label for="user_password">Пароль</label>
                <input type="password" name="password" value="" size="50" class="form-control" id="user_password"
                         placeholder="Ваш пароль"/>
                <input type="hidden" name="next" value="{{ next }}">
                <a href="{% url 'register' %}">Регистрация</a><br>
                <input type="submit" value="Войти" class="btn-sm btn-default"/>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{% block title %}Test Camp - Главная страница{% endblock %}
{% load static %}
{% block logo %}
<div class="navbar-brand">
<a href="#" id="logo">
    Test Camp at SQA Days
  <!--<img src="{% static "img/logo_0205_extra_small.png" %}">-->
</a>
</div>
{% endblock logo %}

{% block section_title %}
{% endblock section_title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            {% if user.is_authenticated %}
                <div id="welcoming-text" class="alert alert-success" role="alert">Вы вошли как <a href="{% url 'cabinet:view_cabinet' user.id %}">
                    {{ user.username }}</a>
                </div>
            {% endif %}
        </div>
    </div>
    <!--<ol class="breadcrumb">
        <li class="active">Главная</li>
    </ol>-->
    <div class="container-fluid text-center bg-grey">
        <!--<h1 id="test">Расписание</h1>-->
        <h1>27 мая</h1>
        <div class="row text-center">
            <div class="col-sm-4">
              <div class="thumbnail">
                  <span class="label label-default">DONE</span>
                  <p>11:10 - 11:55</p>
                  {% with theme="GAMES" %}
                        <a href="{% url 'tasks:theme_tasks' theme %}">
                            <!--<img src="{% static "img/games.png" %}" alt="Games">-->
                            <div id="GAMES">Игры</div>
                        </a>
                {% endwith %}
                <!--<p><strong>Игры!</strong></p>-->
              </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <span class="label label-default">DONE</span>
                  <p>11:55 - 12:45</p>
                  {% with theme="API" %}
                        <a href="{% url 'tasks:theme_tasks' theme %}">
                            <!--<img src="{% static "img/api.png" %}" alt="API">-->
                            <div id="API">Тестирование API</div>
                        </a>
                  {% endwith %}
                <!--<p><strong>Тестирование API</strong></p>-->
              </div>
            </div>
            <div class="col-sm-4">
              <div class="thumbnail">
                  <span class="label label-success">IN PROGRESS</span>
                  <p>12:45 - 13:35</p>
                  {% with theme="GAMES" %}
                        <a href="{% url 'tasks:theme_tasks' theme %}">
                            <!--<img src="{% static "img/games.png" %}" alt="Games">-->
                            <div id="GAMES">Игры</div>
                        </a>
                {% endwith %}
                <!--<p><strong>Игры!</strong></p>-->
              </div>
            </div>
            <div class="col-sm-6">
              <div class="thumbnail">
                <span class="label label-default">COMING SOON</span>
                  <p>14:30 - 15:55</p>
                {% with theme="IOT" %}
                        <a href="{% url 'tasks:theme_tasks' theme %}">
                            <!--<img src="{% static "img/iot.png" %}" alt="IoT">-->
                            <div id="IOT">Internet Of Things</div>
                        </a>
                {% endwith %}
                <!--<p><strong>Internet of Things</strong></p>-->
              </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <span class="label label-default">COMING SOON</span>
                  <p>16:00 - 16:50</p>
                  {% with theme="API" %}
                        <a href="{% url 'tasks:theme_tasks' theme %}">
                            <!--<img src="{% static "img/api.png" %}" alt="API">-->
                            <div id="API">Тестирование API</div>
                        </a>
                  {% endwith %}
                <!--<p><strong>Тестирование API</strong></p>-->
              </div>
            </div>
            <!--<div class="col-sm-3">-->
              <!--<div class="thumbnail">-->
                  <!--<span class="label label-default">COMING SOON</span>-->
                  <!--<p>14:00 - 16:00</p>-->
                  <!--{% with theme="ET" %}-->
                        <!--<a href="{% url 'tasks:theme_tasks' theme %}">-->
                            <!--<img src="{% static "img/et.png" %}">-->
                        <!--</a>-->
                <!--{% endwith %}-->
                <!--<p><strong>ИТ</strong></p>-->
                <!--<p>Старое доброе исследовательское тестирование</p>-->
              <!--</div>-->
            <!--</div>-->
            <!--<div class="col-sm-4">-->
              <!--<div class="thumbnail">-->
                  <!--<span class="label label-default">COMING SOON</span>-->
                  <!--<p>16:00 - 18:00</p>-->
                  <!--{% with theme="GAMES" %}-->
                        <!--<a href="{% url 'tasks:theme_tasks' theme %}">-->
                            <!--&lt;!&ndash;<img src="{% static "img/games.png" %}" alt="Games">&ndash;&gt;-->
                            <!--<div id="GAMES">Игры</div>-->
                        <!--</a>-->
                <!--{% endwith %}-->
                <!--&lt;!&ndash;<p><strong>Игры!</strong></p>&ndash;&gt;-->
              <!--</div>-->
            <!--</div>-->
        <!--</div>-->
        <!--<h1>27 мая</h1>-->
        <!--<h4>Программа формируется</h4>-->
        <!--<p class="glyphicon glyphicon glyphicon-glass" aria-hidden="true"></p>-->
        <!--<span class="glyphicon glyphicon glyphicon-music" aria-hidden="true"></span>-->
        <!--<span class="glyphicon glyphicon glyphicon-star-empty" aria-hidden="true"></span>-->
    </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container">
    {% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li class="active">Регистрация</li>
    </ol>
    {% endblock %}
    {% if registered %}
        <div class="alert alert-success" role="alert">
            <p>Спасибо за регистрацию!</p>
        </div>
    {% else %}
        <form id="user_form" method="post" action="{% url 'register' %}"
            enctype="multipart/form-data">
            <div class="form-group row">
                <div class="col-md-6">
                    {% csrf_token %}
                    {% if user_form.non_field_errors %}
                        <div class="alert alert-warning" role="alert">
                            <p>{{ user_form.non_field_errors }}</p>
                        </div>
                    {% endif %}
                    {% if user_form.username.errors %}
                        <div class="alert alert-warning" role="alert">
                            <p>{{ user_form.username.errors }}</p>
                        </div>
                    {% endif %}
                    <label for="user_name">Имя пользователя</label>
                    <input type="text" name="username" value="" size="50" class="form-control" id="user_name"
                       placeholder="Введите имя"/>
                    {% if user_form.email.errors %}
                        <div class="alert alert-warning" role="alert">
                            <p>{{ user_form.email.errors }}</p>
                        </div>
                    {% endif %}
                    <label for="user_email">E-mail</label>
                    <input type="text" name="email" value="" size="50" class="form-control" id="user_email"
                       placeholder="Введите e-mail"/>
                    {% if user_form.email.errors %}
                        <div class="alert alert-warning" role="alert">
                            <p>{{ user_form.password.errors }}</p>
                        </div>
                    {% endif %}
                    <label for="user_password">Пароль</label>
                    <input type="password" name="password" value="" size="50" class="form-control" id="user_password"
                       placeholder="Введите пароль"/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    {% csrf_token %}
                    {{ profile_form.picture }}
                </div>
            </div>
            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Зарегистрироваться" class="btn btn-default"/>
        </form>
    {% endif %}
</div>
{% endblock %}

templates/stats.html
{% extends "base.html" %}

{% load static %}
{% block custom_static %}
    <!-- Custom styles for this template -->
    <link href="{% static "css/jumbotron-narrow.css" %}" rel="stylesheet">
{% endblock custom_static %}

{% block title %}Статистика{% endblock %}

{% block content %}
<div class="container">
    {% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li class="active">Статистика</li>
    </ol>
    {% endblock %}
</div>
{% endblock %}

templates/task_base_template.html
{% extends "base.html" %}

{% load static %}
{% block custom_static %}
    <!-- Custom styles for this template -->
    <script src='{% static "js/react.js" %}'></script>
    <script src='{% static "js/react-dom.js" %}'></script>
    <!--<script src='{% static "js/require.js" %}'></script>-->
    <!--<script src='https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.24/browser.js'></script>-->
    <script src='{% static "js/browser_babel.js" %}'></script>
{% endblock custom_static %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
<div class="container">
    {% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'main' %}">Главная</a></li>
        <li><a href="{% url 'tasks:tasks' %}">Задания</a></li>
        <li><a href="{% url 'tasks:theme_tasks' task.task_theme.theme_code %}">{{ task.task_theme.theme_code }}</a></li>
        <li class="active">{{ task.title }}</li>
    </ol>
    {% endblock %}
    {% block button_panel %}
        <div class="panel panel-default">
            <div class="panel-body">
                {% if task.task_theme.theme_status != "in_progress" and status.state != 'FINISHED' %}
                    Шаги выполнения пока не доступны, так как тема задачи неактивна.
                    Пожалуйста дождитесь, когда тема начнется по расписанию.
                {% else %}
                {% if status.state == "IDLE" %}
                    <div class="alert alert-info alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p class="task_help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Для того, чтобы увидеть шаги выполнения задания, а также информацию и подсказки, нажмите на "Начать".</p>
                        <p class="task_help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Для того, чтобы приостановить выполнение задания, нажмите на "Остановить". Чтобы продолжить выполнение после остановки - нажмите "Продолжить".</li>
                        <p class="task_help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Если вы считаете задание выполненным - нажмите на "Завершить". После завершения задания информация о задании остается доступной.</li>
                    </div>
                {% elif status.state != "FINISHED" %}
                    <button role="button" class="btn btn-default btn-sm" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </button>
                    <div class="alert alert-info collapse" role="alert" id="collapseExample">
                        <p class="task_help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Для того, чтобы увидеть шаги выполнения задания, а также информацию и подсказки, нажмите на "Начать".</p>
                        <p class="task_help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Для того, чтобы приостановить выполнение задания, нажмите на "Остановить". Чтобы продолжить выполнение после остановки - нажмите "Продолжить".</li>
                        <p class="task_help"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Если вы считаете задание выполненным - нажмите на "Завершить". После завершения задания информация о задании остается доступной.</li>
                    </div>
                {% endif %}
                    <div id="task_panel">
                    </div>
                {% endif %}
            </div>
        </div>
    {% endblock %}
    {% block task_title%}
    <div class="page-header">
            <h3>{{ task.task_theme.theme_code }}-{{task.code}}: {{ task.title }}</h3>
        </div>
    {% endblock %}
    {% block task_content%}
        {% if linked_task %}
            <p>
            Связанная задача: <a href="{% url 'tasks:task' linked_task.id %}">{{ linked_task.task_theme.theme_code }}-{{ linked_task.code }}: {{ linked_task.title }} </a>
            </p>
        {% endif %}
        <div class="well">
            {{ task.description }}
        </div>
        {% if task.task_theme.theme_status == "in_progress" %}
            {% if linked_task_finished or not linked_task %}
                {% block task_information %}
                {% endblock %}
            {% endif %}
        {% endif %}
    {% endblock %}
</div>
{% endblock %}

{% block more_scripts %}
    <script>
        var task_status = "{{ status.state }}";
        var user_is_authenticated = 0;
        {% if user.is_authenticated %}
            user_is_authenticated = 1;
        {% else %}
            user_is_authenticated = 0;
        {% endif %}
        var start_time = 0, comeback_time = 0;
        {% if status.comeback_time %}
            comeback_time = "{{ status.comeback_time.isoformat }}";
        {% endif %}
        {% if status.start_time %}
            start_time = "{{ status.start_time.isoformat }}";
        {% endif %}
        var duration = "{{ status.duration }}";
        var stop_link = "{% url 'tasks:stop' task.id %}";
        var start_link = "{% url 'tasks:start' task.id %}";
        var continue_link = "{% url 'tasks:come_back' task.id %}";
        var finish_link = "{% url 'tasks:finish' task.id %}";
        var linked_task = 0, linked_task_finished = 0;
        {% if linked_task %}
            linked_task = 1;
        {% endif %}
        {% if linked_task_finished %}
            linked_task_finished = 1;
        {% endif %}
        var dependant_task = 0;
        var dependant_task_link, dependant_task_code, dependant_task_title;
        {% if dependant_task %}
            dependant_task = 1;
            dependant_task_link = "{% url 'tasks:task' dependant_task.id %}";
            dependant_task_code = "{{ dependant_task.task_theme.theme_code }}" + "-" + "{{ dependant_task.code }}";
            dependant_task_title = "{{ dependant_task.title }}";
         {% endif %}
    </script>
    <script src='{% static "js/moment.js" %}'></script>
        <script>
            moment().format();
    </script>
    <script src='{% static "js/task_panel.js" %}' type="text/babel"></script>
{% endblock more_scripts %}